version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore: "
